/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.DedicatedWorkerRealmInfo command
 */
public class DedicatedWorkerRealmInfo implements RealmInfo {

    /**
     * Creates a new DedicatedWorkerRealmInfo instance
     */
    public DedicatedWorkerRealmInfo(List<String> owners) {
        this.owners = owners;
        this.type = "dedicated-worker";
    }

    private final String type;

    /**
     * Gets the type property
     * @return String value
     */
    public String getType() {
        return this.type;
    }

    private final List<String> owners;

    /**
     * Gets the owners property
     * @return List<String> value
     */
    public List<String> getOwners() {
        return this.owners;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("type", this.type);
        toReturn.put("owners", this.owners);
        return toReturn;
    }

}