/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.DisownParameters command
 */
public class DisownParameters {

    /**
     * Creates a new DisownParameters instance
     */
    public DisownParameters(List<String> handles, Script.Target target) {
        this.handles = handles;
        this.target = target;
    }

    private final List<String> handles;

    /**
     * Gets the handles property
     * @return List<String> value
     */
    public List<String> getHandles() {
        return this.handles;
    }

    private final Script.Target target;

    /**
     * Gets the target property
     * @return Script.Target value
     */
    public Script.Target getTarget() {
        return this.target;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("handles", this.handles);
        toReturn.put("target", this.target);
        return toReturn;
    }

}