/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.EvaluateParameters command
 */
public class EvaluateParameters {

    /**
     * Creates a new EvaluateParameters instance
     */
    public EvaluateParameters(String expression, Script.Target target, Boolean awaitPromise, Script.ResultOwnership resultOwnership, Script.SerializationOptions serializationOptions, Boolean userActivation) {
        this.expression = expression;
        this.target = target;
        this.awaitPromise = awaitPromise;
        this.resultOwnership = resultOwnership;
        this.serializationOptions = serializationOptions;
        this.userActivation = userActivation;
    }

    private final String expression;

    /**
     * Gets the expression property
     * @return String value
     */
    public String getExpression() {
        return this.expression;
    }

    private final Script.Target target;

    /**
     * Gets the target property
     * @return Script.Target value
     */
    public Script.Target getTarget() {
        return this.target;
    }

    private final Boolean awaitPromise;

    /**
     * Gets the awaitPromise property
     * @return Boolean value
     */
    public Boolean getAwaitPromise() {
        return this.awaitPromise;
    }

    private final Script.ResultOwnership resultOwnership;

    /**
     * Gets the resultOwnership property
     * @return Script.ResultOwnership value
     */
    public Script.ResultOwnership getResultOwnership() {
        return this.resultOwnership;
    }

    private final Script.SerializationOptions serializationOptions;

    /**
     * Gets the serializationOptions property
     * @return Script.SerializationOptions value
     */
    public Script.SerializationOptions getSerializationOptions() {
        return this.serializationOptions;
    }

    private final Boolean userActivation;

    /**
     * Gets the userActivation property
     * @return Boolean value
     */
    public Boolean getUserActivation() {
        return this.userActivation;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("expression", this.expression);
        toReturn.put("target", this.target);
        toReturn.put("awaitPromise", this.awaitPromise);
        toReturn.put("resultOwnership", this.resultOwnership);
        toReturn.put("serializationOptions", this.serializationOptions);
        toReturn.put("userActivation", this.userActivation);
        return toReturn;
    }

}