/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents enum for script.EvaluateResult which can be either of these classes:
 *   - script.EvaluateResultSuccess
 *   - script.EvaluateResultException
 */
public class EvaluateResult {

}