/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.EvaluateResultException command
 */
public class EvaluateResultException implements EvaluateResult {

    /**
     * Creates a new EvaluateResultException instance
     */
    public EvaluateResultException(Script.ExceptionDetails exceptionDetails, String realm) {
        this.exceptionDetails = exceptionDetails;
        this.realm = realm;
        this.type = "exception";
    }

    private final String type;

    /**
     * Gets the type property
     * @return String value
     */
    public String getType() {
        return this.type;
    }

    private final Script.ExceptionDetails exceptionDetails;

    /**
     * Gets the exceptionDetails property
     * @return Script.ExceptionDetails value
     */
    public Script.ExceptionDetails getExceptionDetails() {
        return this.exceptionDetails;
    }

    private final String realm;

    /**
     * Gets the realm property
     * @return String value
     */
    public String getRealm() {
        return this.realm;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("type", this.type);
        toReturn.put("exceptionDetails", this.exceptionDetails);
        toReturn.put("realm", this.realm);
        return toReturn;
    }

}