/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.GetRealmsResult command
 */
public class GetRealmsResult implements ScriptResult {

    /**
     * Creates a new GetRealmsResult instance
     */
    public GetRealmsResult(List<Script.RealmInfo> realms) {
        this.realms = realms;
    }

    private final List<Script.RealmInfo> realms;

    /**
     * Gets the realms property
     * @return List<Script.RealmInfo> value
     */
    public List<Script.RealmInfo> getRealms() {
        return this.realms;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("realms", this.realms);
        return toReturn;
    }

}