/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents enum for script.LocalValue which can be either of these classes:
 *   - script.RemoteReference
 *   - script.PrimitiveProtocolValue
 *   - script.ChannelValue
 *   - script.ArrayLocalValue
 *   - script.DateLocalValue
 *   - script.MapLocalValue
 *   - script.ObjectLocalValue
 *   - script.RegExpLocalValue
 *   - script.SetLocalValue
 */
public class LocalValue {

}