/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.MessageParameters command
 */
public class MessageParameters {

    /**
     * Creates a new MessageParameters instance
     */
    public MessageParameters(String channel, Script.RemoteValue data, Script.Source source) {
        this.channel = channel;
        this.data = data;
        this.source = source;
    }

    private final String channel;

    /**
     * Gets the channel property
     * @return String value
     */
    public String getChannel() {
        return this.channel;
    }

    private final Script.RemoteValue data;

    /**
     * Gets the data property
     * @return Script.RemoteValue value
     */
    public Script.RemoteValue getData() {
        return this.data;
    }

    private final Script.Source source;

    /**
     * Gets the source property
     * @return Script.Source value
     */
    public Script.Source getSource() {
        return this.source;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("channel", this.channel);
        toReturn.put("data", this.data);
        toReturn.put("source", this.source);
        return toReturn;
    }

}