/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.NodeRemoteValue command
 */
public class NodeRemoteValue implements RemoteValue {

    /**
     * Creates a new NodeRemoteValue instance
     */
    public NodeRemoteValue(String sharedId, String handle, String internalId, Script.NodeProperties value) {
        this.sharedId = sharedId;
        this.handle = handle;
        this.internalId = internalId;
        this.value = value;
        this.type = "node";
    }

    private final String type;

    /**
     * Gets the type property
     * @return String value
     */
    public String getType() {
        return this.type;
    }

    private final String sharedId;

    /**
     * Gets the sharedId property
     * @return String value
     */
    public String getSharedId() {
        return this.sharedId;
    }

    private final String handle;

    /**
     * Gets the handle property
     * @return String value
     */
    public String getHandle() {
        return this.handle;
    }

    private final String internalId;

    /**
     * Gets the internalId property
     * @return String value
     */
    public String getInternalId() {
        return this.internalId;
    }

    private final Script.NodeProperties value;

    /**
     * Gets the value property
     * @return Script.NodeProperties value
     */
    public Script.NodeProperties getValue() {
        return this.value;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("type", this.type);
        toReturn.put("sharedId", this.sharedId);
        toReturn.put("handle", this.handle);
        toReturn.put("internalId", this.internalId);
        toReturn.put("value", this.value);
        return toReturn;
    }

}