/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents RealmType in WebDriver BiDi protocol
 * as enum of "window" / "dedicated-worker" / "shared-worker" / "service-worker" / "worker" / "paint-worklet" / "audio-worklet" / "worklet"
 */
public enum RealmType {
    WINDOW("window");
    DEDICATED-WORKER("dedicated-worker");
    SHARED-WORKER("shared-worker");
    SERVICE-WORKER("service-worker");
    WORKER("worker");
    PAINT-WORKLET("paint-worklet");
    AUDIO-WORKLET("audio-worklet");
    WORKLET("worklet");

    private final String value;

    RealmType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static RealmType fromString(String text) {
        for (RealmType realmtype : RealmType.values()) {
            if (realmtype.value.equalsIgnoreCase(text)) {
                return realmtype;
            }
        }
        throw new IllegalArgumentException("No RealmType with value: " + text);
    }
}