/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.RealmDestroyedParameters command
 */
public class RealmDestroyedParameters {

    /**
     * Creates a new RealmDestroyedParameters instance
     */
    public RealmDestroyedParameters(String realm) {
        this.realm = realm;
    }

    private final String realm;

    /**
     * Gets the realm property
     * @return String value
     */
    public String getRealm() {
        return this.realm;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("realm", this.realm);
        return toReturn;
    }

}