/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.RemoteObjectReference command
 */
public class RemoteObjectReference implements RemoteReference {

    /**
     * Creates a new RemoteObjectReference instance
     */
    public RemoteObjectReference(String handle, String sharedId) {
        this.handle = handle;
        this.sharedId = sharedId;
    }

    private final String handle;

    /**
     * Gets the handle property
     * @return String value
     */
    public String getHandle() {
        return this.handle;
    }

    private final String sharedId;

    /**
     * Gets the sharedId property
     * @return String value
     */
    public String getSharedId() {
        return this.sharedId;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("handle", this.handle);
        toReturn.put("sharedId", this.sharedId);
        return toReturn;
    }

}