/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.script;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for script.SerializationOptions command
 */
public class SerializationOptions {

    /**
     * Creates a new SerializationOptions instance
     */
    public SerializationOptions(Object maxDomDepth, Object maxObjectDepth, Object includeShadowTree) {
        this.maxDomDepth = maxDomDepth;
        this.maxObjectDepth = maxObjectDepth;
        this.includeShadowTree = includeShadowTree;
    }

    private final Object maxDomDepth;

    /**
     * Gets the maxDomDepth property
     * @return Object value
     */
    public Object getMaxDomDepth() {
        return this.maxDomDepth;
    }

    private final Object maxObjectDepth;

    /**
     * Gets the maxObjectDepth property
     * @return Object value
     */
    public Object getMaxObjectDepth() {
        return this.maxObjectDepth;
    }

    private final Object includeShadowTree;

    /**
     * Gets the includeShadowTree property
     * @return Object value
     */
    public Object getIncludeShadowTree() {
        return this.includeShadowTree;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("maxDomDepth", this.maxDomDepth);
        toReturn.put("maxObjectDepth", this.maxObjectDepth);
        toReturn.put("includeShadowTree", this.includeShadowTree);
        return toReturn;
    }

}