/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.session;

import java.util.Map;
import java.util.HashMap;

/**
 * Represents browser capabilities in WebDriver BiDi protocol
 */
public class Capabilities {
    private final Map<String, Object> capabilities;

    public Capabilities(Map<String, Object> capabilities) {
        this.capabilities = capabilities != null ? capabilities : new HashMap<>();
    }

    public Boolean getAcceptInsecureCerts() {
        return (Boolean) capabilities.get("acceptInsecureCerts");
    }

    public String getBrowserName() {
        return (String) capabilities.get("browserName");
    }

    public String getBrowserVersion() {
        return (String) capabilities.get("browserVersion");
    }

    public String getPlatformName() {
        return (String) capabilities.get("platformName");
    }

    public Boolean getSetWindowRect() {
        return (Boolean) capabilities.get("setWindowRect");
    }

    public String getUserAgent() {
        return (String) capabilities.get("userAgent");
    }

    public String getWebSocketUrl() {
        return (String) capabilities.get("webSocketUrl");
    }

    public Map<String, Object> asMap() {
        return new HashMap<>(capabilities);
    }
}