/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.session;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for session.CapabilitiesRequest command
 */
public class CapabilitiesRequest {

    /**
     * Creates a new CapabilitiesRequest instance
     */
    public CapabilitiesRequest(Session.CapabilityRequest alwaysMatch, List<Session.CapabilityRequest> firstMatch) {
        this.alwaysMatch = alwaysMatch;
        this.firstMatch = firstMatch;
    }

    private final Session.CapabilityRequest alwaysMatch;

    /**
     * Gets the alwaysMatch property
     * @return Session.CapabilityRequest value
     */
    public Session.CapabilityRequest getAlwaysMatch() {
        return this.alwaysMatch;
    }

    private final List<Session.CapabilityRequest> firstMatch;

    /**
     * Gets the firstMatch property
     * @return List<Session.CapabilityRequest> value
     */
    public List<Session.CapabilityRequest> getFirstMatch() {
        return this.firstMatch;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("alwaysMatch", this.alwaysMatch);
        toReturn.put("firstMatch", this.firstMatch);
        return toReturn;
    }

}