/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.session;

import java.util.Map;
import java.util.HashMap;
import org.openqa.selenium.bidi.Command;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto generated class for running WebDriver BiDi session commands in Java
 */
public class SessionModule {

    /**
     * WebDriver Bidi command to send command method "session.unsubscribe" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-session-unsubscribe
     * @param parameters `UnsubscribeParameters` {@link https://w3c.github.io/webdriver-bidi/#command-session-unsubscribe | command parameter}
     * @return Command object with result type for session.unsubscribe
     */
    public Command<org.openqa.selenium.bidirectional.EmptyResult> Unsubscribe (UnsubscribeParameters parameters) {
        return new Command<>(
            "session.unsubscribe",
            parameters.asMap(),
            org.openqa.selenium.bidirectional.EmptyResult.class
        );
    }
}