/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.webextension;

import java.util.Map;
import java.util.HashMap;
import org.openqa.selenium.bidi.Command;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto generated class for running WebDriver BiDi webextension commands in Java
 */
public class WebExtensionModule {

    /**
     * WebDriver Bidi command to send command method "webExtension.uninstall" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-webExtension-uninstall
     * @param parameters `UninstallParameters` {@link https://w3c.github.io/webdriver-bidi/#command-webExtension-uninstall | command parameter}
     * @return Command object with result type for webExtension.uninstall
     */
    public Command<org.openqa.selenium.bidirectional.EmptyResult> Uninstall (UninstallParameters parameters) {
        return new Command<>(
            "webExtension.uninstall",
            parameters.asMap(),
            org.openqa.selenium.bidirectional.EmptyResult.class
        );
    }
}