/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browser;

import java.util.Map;
import java.util.HashMap;
import org.openqa.selenium.bidi.Command;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto generated class for running WebDriver BiDi browser commands in Java
 */
public class BrowserModule {

    /**
     * WebDriver Bidi command to send command method "browser.setClientWindowState" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-browser-setClientWindowState
     * @param parameters `SetClientWindowStateParameters` {@link https://w3c.github.io/webdriver-bidi/#command-browser-setClientWindowState | command parameter}
     * @return Command object with result type for browser.setClientWindowState
     */
    public Command<org.openqa.selenium.bidirectional.EmptyResult> SetClientWindowState (SetClientWindowStateParameters parameters) {
        return new Command<>(
            "browser.setClientWindowState",
            parameters.asMap(),
            org.openqa.selenium.bidirectional.EmptyResult.class
        );
    }
}