/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.BaseNavigationInfo command
 */
public class BaseNavigationInfo {

    /**
     * Creates a new BaseNavigationInfo instance
     */
    public BaseNavigationInfo(String context, Object navigation, Long timestamp, String url) {
        this.context = context;
        this.navigation = navigation;
        this.timestamp = timestamp;
        this.url = url;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final Object navigation;

    /**
     * Gets the navigation property
     * @return Object value
     */
    public Object getNavigation() {
        return this.navigation;
    }

    private final Long timestamp;

    /**
     * Gets the timestamp property
     * @return Long value
     */
    public Long getTimestamp() {
        return this.timestamp;
    }

    private final String url;

    /**
     * Gets the url property
     * @return String value
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("navigation", this.navigation);
        toReturn.put("timestamp", this.timestamp);
        toReturn.put("url", this.url);
        return toReturn;
    }

}