/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents CreateType in WebDriver BiDi protocol
 * as enum of "tab" / "window"
 */
public enum CreateType {
    TAB("tab");
    WINDOW("window");

    private final String value;

    CreateType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static CreateType fromString(String text) {
        for (CreateType createtype : CreateType.values()) {
            if (createtype.value.equalsIgnoreCase(text)) {
                return createtype;
            }
        }
        throw new IllegalArgumentException("No CreateType with value: " + text);
    }
}