/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.HandleUserPromptParameters command
 */
public class HandleUserPromptParameters {

    /**
     * Creates a new HandleUserPromptParameters instance
     */
    public HandleUserPromptParameters(String context, Boolean accept, String userText) {
        this.context = context;
        this.accept = accept;
        this.userText = userText;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final Boolean accept;

    /**
     * Gets the accept property
     * @return Boolean value
     */
    public Boolean getAccept() {
        return this.accept;
    }

    private final String userText;

    /**
     * Gets the userText property
     * @return String value
     */
    public String getUserText() {
        return this.userText;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("accept", this.accept);
        toReturn.put("userText", this.userText);
        return toReturn;
    }

}