/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.NavigateParameters command
 */
public class NavigateParameters {

    /**
     * Creates a new NavigateParameters instance
     */
    public NavigateParameters(String context, String url, BrowsingContext.ReadinessState wait) {
        this.context = context;
        this.url = url;
        this.wait = wait;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final String url;

    /**
     * Gets the url property
     * @return String value
     */
    public String getUrl() {
        return this.url;
    }

    private final BrowsingContext.ReadinessState wait;

    /**
     * Gets the wait property
     * @return BrowsingContext.ReadinessState value
     */
    public BrowsingContext.ReadinessState getWait() {
        return this.wait;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("url", this.url);
        toReturn.put("wait", this.wait);
        return toReturn;
    }

}