/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents ReadinessState in WebDriver BiDi protocol
 * as enum of "none" / "interactive" / "complete"
 */
public enum ReadinessState {
    NONE("none");
    INTERACTIVE("interactive");
    COMPLETE("complete");

    private final String value;

    ReadinessState(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static ReadinessState fromString(String text) {
        for (ReadinessState readinessstate : ReadinessState.values()) {
            if (readinessstate.value.equalsIgnoreCase(text)) {
                return readinessstate;
            }
        }
        throw new IllegalArgumentException("No ReadinessState with value: " + text);
    }
}