/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.ReloadParameters command
 */
public class ReloadParameters {

    /**
     * Creates a new ReloadParameters instance
     */
    public ReloadParameters(String context, Boolean ignoreCache, BrowsingContext.ReadinessState wait) {
        this.context = context;
        this.ignoreCache = ignoreCache;
        this.wait = wait;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final Boolean ignoreCache;

    /**
     * Gets the ignoreCache property
     * @return Boolean value
     */
    public Boolean getIgnoreCache() {
        return this.ignoreCache;
    }

    private final BrowsingContext.ReadinessState wait;

    /**
     * Gets the wait property
     * @return BrowsingContext.ReadinessState value
     */
    public BrowsingContext.ReadinessState getWait() {
        return this.wait;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("ignoreCache", this.ignoreCache);
        toReturn.put("wait", this.wait);
        return toReturn;
    }

}