/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.browsingcontext;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for browsingContext.TraverseHistoryParameters command
 */
public class TraverseHistoryParameters {

    /**
     * Creates a new TraverseHistoryParameters instance
     */
    public TraverseHistoryParameters(String context, Integer delta) {
        this.context = context;
        this.delta = delta;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final Integer delta;

    /**
     * Gets the delta property
     * @return Integer value
     */
    public Integer getDelta() {
        return this.delta;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("delta", this.delta);
        return toReturn;
    }

}