import fs from 'node:fs/promises'
import url from 'node:url'
import path from 'node:path'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))
export const pkg = JSON.parse(await fs.readFile(path.join(__dirname, '..', 'package.json'), 'utf-8'))

export const GENERATED_FILE_COMMENT = `/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */`

export const CDDL_PARSE_ERROR_MESSAGE = `
====================
CDDL PARSING FAILED!
====================

No updates to the CDDL interface can be applied as the script failed to parse
the spec CDDL due to the following error:

%s
`