/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for network.AddInterceptParameters command
 */
public class AddInterceptParameters {

    /**
     * Creates a new AddInterceptParameters instance
     */
    public AddInterceptParameters(List<Network.InterceptPhase> phases, List<String> contexts, List<Network.UrlPattern> urlPatterns) {
        this.phases = phases;
        this.contexts = contexts;
        this.urlPatterns = urlPatterns;
    }

    private final List<Network.InterceptPhase> phases;

    /**
     * Gets the phases property
     * @return List<Network.InterceptPhase> value
     */
    public List<Network.InterceptPhase> getPhases() {
        return this.phases;
    }

    private final List<String> contexts;

    /**
     * Gets the contexts property
     * @return List<String> value
     */
    public List<String> getContexts() {
        return this.contexts;
    }

    private final List<Network.UrlPattern> urlPatterns;

    /**
     * Gets the urlPatterns property
     * @return List<Network.UrlPattern> value
     */
    public List<Network.UrlPattern> getUrlPatterns() {
        return this.urlPatterns;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("phases", this.phases);
        toReturn.put("contexts", this.contexts);
        toReturn.put("urlPatterns", this.urlPatterns);
        return toReturn;
    }

}