/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for network.ContinueWithAuthParameters command
 */
public class ContinueWithAuthParameters {

    /**
     * Creates a new ContinueWithAuthParameters instance
     */
    public ContinueWithAuthParameters(String request) {
        this.request = request;
    }

    private final String request;

    /**
     * Gets the request property
     * @return String value
     */
    public String getRequest() {
        return this.request;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("request", this.request);
        return toReturn;
    }

}