/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents InterceptPhase in WebDriver BiDi protocol
 * as enum of "beforeRequestSent" / "responseStarted" / "authRequired"
 */
public enum InterceptPhase {
    BEFOREREQUESTSENT("beforeRequestSent");
    RESPONSESTARTED("responseStarted");
    AUTHREQUIRED("authRequired");

    private final String value;

    InterceptPhase(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static InterceptPhase fromString(String text) {
        for (InterceptPhase interceptphase : InterceptPhase.values()) {
            if (interceptphase.value.equalsIgnoreCase(text)) {
                return interceptphase;
            }
        }
        throw new IllegalArgumentException("No InterceptPhase with value: " + text);
    }
}