/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import java.util.Map;
import java.util.HashMap;
import org.openqa.selenium.bidi.Command;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto generated class for running WebDriver BiDi network commands in Java
 */
public class NetworkModule {

    /**
     * WebDriver Bidi command to send command method "network.setCacheBehavior" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-network-setCacheBehavior
     * @param parameters `SetCacheBehaviorParameters` {@link https://w3c.github.io/webdriver-bidi/#command-network-setCacheBehavior | command parameter}
     * @return Command object with result type for network.setCacheBehavior
     */
    public Command<org.openqa.selenium.bidirectional.EmptyResult> SetCacheBehavior (SetCacheBehaviorParameters parameters) {
        return new Command<>(
            "network.setCacheBehavior",
            parameters.asMap(),
            org.openqa.selenium.bidirectional.EmptyResult.class
        );
    }
}