/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for network.RequestData command
 */
public class RequestData {

    /**
     * Creates a new RequestData instance
     */
    public RequestData(String request, String url, String method, List<Network.Header> headers, List<Network.Cookie> cookies, Long headersSize, Object bodySize, String destination, Object initiatorType, Network.FetchTimingInfo timings) {
        this.request = request;
        this.url = url;
        this.method = method;
        this.headers = headers;
        this.cookies = cookies;
        this.headersSize = headersSize;
        this.bodySize = bodySize;
        this.destination = destination;
        this.initiatorType = initiatorType;
        this.timings = timings;
    }

    private final String request;

    /**
     * Gets the request property
     * @return String value
     */
    public String getRequest() {
        return this.request;
    }

    private final String url;

    /**
     * Gets the url property
     * @return String value
     */
    public String getUrl() {
        return this.url;
    }

    private final String method;

    /**
     * Gets the method property
     * @return String value
     */
    public String getMethod() {
        return this.method;
    }

    private final List<Network.Header> headers;

    /**
     * Gets the headers property
     * @return List<Network.Header> value
     */
    public List<Network.Header> getHeaders() {
        return this.headers;
    }

    private final List<Network.Cookie> cookies;

    /**
     * Gets the cookies property
     * @return List<Network.Cookie> value
     */
    public List<Network.Cookie> getCookies() {
        return this.cookies;
    }

    private final Long headersSize;

    /**
     * Gets the headersSize property
     * @return Long value
     */
    public Long getHeadersSize() {
        return this.headersSize;
    }

    private final Object bodySize;

    /**
     * Gets the bodySize property
     * @return Object value
     */
    public Object getBodySize() {
        return this.bodySize;
    }

    private final String destination;

    /**
     * Gets the destination property
     * @return String value
     */
    public String getDestination() {
        return this.destination;
    }

    private final Object initiatorType;

    /**
     * Gets the initiatorType property
     * @return Object value
     */
    public Object getInitiatorType() {
        return this.initiatorType;
    }

    private final Network.FetchTimingInfo timings;

    /**
     * Gets the timings property
     * @return Network.FetchTimingInfo value
     */
    public Network.FetchTimingInfo getTimings() {
        return this.timings;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("request", this.request);
        toReturn.put("url", this.url);
        toReturn.put("method", this.method);
        toReturn.put("headers", this.headers);
        toReturn.put("cookies", this.cookies);
        toReturn.put("headersSize", this.headersSize);
        toReturn.put("bodySize", this.bodySize);
        toReturn.put("destination", this.destination);
        toReturn.put("initiatorType", this.initiatorType);
        toReturn.put("timings", this.timings);
        return toReturn;
    }

}