/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents SameSite in WebDriver BiDi protocol
 * as enum of "strict" / "lax" / "none"
 */
public enum SameSite {
    STRICT("strict");
    LAX("lax");
    NONE("none");

    private final String value;

    SameSite(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static SameSite fromString(String text) {
        for (SameSite samesite : SameSite.values()) {
            if (samesite.value.equalsIgnoreCase(text)) {
                return samesite;
            }
        }
        throw new IllegalArgumentException("No SameSite with value: " + text);
    }
}