/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.network;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for network.SetCacheBehaviorParameters command
 */
public class SetCacheBehaviorParameters {

    /**
     * Creates a new SetCacheBehaviorParameters instance
     */
    public SetCacheBehaviorParameters(Object cacheBehavior, List<String> contexts) {
        this.cacheBehavior = cacheBehavior;
        this.contexts = contexts;
    }

    private final Object cacheBehavior;

    /**
     * Gets the cacheBehavior property
     * @return Object value
     */
    public Object getCacheBehavior() {
        return this.cacheBehavior;
    }

    private final List<String> contexts;

    /**
     * Gets the contexts property
     * @return List<String> value
     */
    public List<String> getContexts() {
        return this.contexts;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("cacheBehavior", this.cacheBehavior);
        toReturn.put("contexts", this.contexts);
        return toReturn;
    }

}