/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional;

import java.util.Map;
import java.util.HashMap;

/**
 * Represents a value with accessibility properties in WebDriver BiDi protocol
 */
public class AccessibilityValue {
    private final String name;
    private final String role;
    private final Map<String, Object> additionalProperties = new HashMap<>();

    /**
     * Creates a new AccessibilityValue instance
     * @param name The accessible name
     * @param role The accessible role
     */
    public AccessibilityValue(String name, String role) {
        this.name = name;
        this.role = role;
    }

    /**
     * Gets the name property
     * @return Name value
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the role property
     * @return Role value
     */
    public String getRole() {
        return role;
    }

    /**
     * Adds an additional property to this value
     * @param key Property name
     * @param value Property value
     */
    public void addProperty(String key, Object value) {
        additionalProperties.put(key, value);
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> result = new HashMap<>(additionalProperties);
        if (name != null) {
            result.put("name", name);
        }
        if (role != null) {
            result.put("role", role);
        }
        return result;
    }
}