/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional;

import java.util.Map;
import java.util.HashMap;

/**
 * Represents a value with context in WebDriver BiDi protocol
 */
public class ContextValue {
    private final String context;
    private final Map<String, Object> additionalProperties = new HashMap<>();

    /**
     * Creates a new ContextValue instance
     * @param context The context ID (typically a browsing context ID)
     */
    public ContextValue(String context) {
        this.context = context;
    }

    /**
     * Gets the context property
     * @return Context ID value
     */
    public String getContext() {
        return context;
    }

    /**
     * Adds an additional property to this value
     * @param key Property name
     * @param value Property value
     */
    public void addProperty(String key, Object value) {
        additionalProperties.put(key, value);
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> result = new HashMap<>(additionalProperties);
        result.put("context", context);
        return result;
    }
}