/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional;

/**
 * Represents an empty result from a WebDriver BiDi command
 */
public class EmptyResult {
    /**
     * Creates a new EmptyResult instance
     */
    public EmptyResult() {
        // Empty result has no properties
    }
}
