import fs from 'node:fs/promises'
import url from 'node:url'
import path from 'node:path'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))
export const pkg = JSON.parse(await fs.readFile(path.join(__dirname, '..', 'package.json'), 'utf-8'))

export const GENERATED_FILE_COMMENT = `# Auto-generated by cddl2py v${pkg.version}\n# Do not edit manually.\n`

export const NATIVE_TYPE_MAP: Record<string, string> = {
    any: 'Any',
    number: 'Union[int, float]',
    int: 'int',
    uint: 'int',
    nint: 'int',
    float: 'float',
    float16: 'float',
    float32: 'float',
    float64: 'float',
    bool: 'bool',
    bstr: 'bytes',
    bytes: 'bytes',
    tstr: 'str',
    text: 'str',
    str: 'str',
    nil: 'None',
    null: 'None',
}

export const PYDANTIC_NATIVE_TYPE_MAP: Record<string, string> = {
    ...NATIVE_TYPE_MAP,
}
