/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents Origin in WebDriver BiDi protocol
 * as enum of "viewport" / "pointer" / "Input.ElementOrigin"
 */
public enum Origin {
    VIEWPORT("viewport");
    POINTER("pointer");
    ELEMENTORIGIN(ElementOrigin.class);

    private final String value;

    Origin(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static Origin fromString(String text) {
        for (Origin origin : Origin.values()) {
            if (origin.value.equalsIgnoreCase(text)) {
                return origin;
            }
        }
        throw new IllegalArgumentException("No Origin with value: " + text);
    }
}