/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for input.PerformActionsParameters command
 */
public class PerformActionsParameters {

    /**
     * Creates a new PerformActionsParameters instance
     */
    public PerformActionsParameters(String context, List<Input.SourceActions> actions) {
        this.context = context;
        this.actions = actions;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final List<Input.SourceActions> actions;

    /**
     * Gets the actions property
     * @return List<Input.SourceActions> value
     */
    public List<Input.SourceActions> getActions() {
        return this.actions;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("actions", this.actions);
        return toReturn;
    }

}