/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents PointerType in WebDriver BiDi protocol
 * as enum of "mouse" / "pen" / "touch"
 */
public enum PointerType {
    MOUSE("mouse");
    PEN("pen");
    TOUCH("touch");

    private final String value;

    PointerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static PointerType fromString(String text) {
        for (PointerType pointertype : PointerType.values()) {
            if (pointertype.value.equalsIgnoreCase(text)) {
                return pointertype;
            }
        }
        throw new IllegalArgumentException("No PointerType with value: " + text);
    }
}