/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for input.PointerCommonProperties command
 */
public class PointerCommonProperties {

    /**
     * Creates a new PointerCommonProperties instance
     */
    public PointerCommonProperties(Long width, Long height, Float pressure, Float tangentialPressure, Float twist, Float altitudeAngle, Float azimuthAngle) {
        this.width = width;
        this.height = height;
        this.pressure = pressure;
        this.tangentialPressure = tangentialPressure;
        this.twist = twist;
        this.altitudeAngle = altitudeAngle;
        this.azimuthAngle = azimuthAngle;
    }

    private final Long width;

    /**
     * Gets the width property
     * @return Long value
     */
    public Long getWidth() {
        return this.width;
    }

    private final Long height;

    /**
     * Gets the height property
     * @return Long value
     */
    public Long getHeight() {
        return this.height;
    }

    private final Float pressure;

    /**
     * Gets the pressure property
     * @return Float value
     */
    public Float getPressure() {
        return this.pressure;
    }

    private final Float tangentialPressure;

    /**
     * Gets the tangentialPressure property
     * @return Float value
     */
    public Float getTangentialPressure() {
        return this.tangentialPressure;
    }

    private final Float twist;

    /**
     * Gets the twist property
     * @return Float value
     */
    public Float getTwist() {
        return this.twist;
    }

    private final Float altitudeAngle;

    /**
     * Gets the altitudeAngle property
     * @return Float value
     */
    public Float getAltitudeAngle() {
        return this.altitudeAngle;
    }

    private final Float azimuthAngle;

    /**
     * Gets the azimuthAngle property
     * @return Float value
     */
    public Float getAzimuthAngle() {
        return this.azimuthAngle;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("width", this.width);
        toReturn.put("height", this.height);
        toReturn.put("pressure", this.pressure);
        toReturn.put("tangentialPressure", this.tangentialPressure);
        toReturn.put("twist", this.twist);
        toReturn.put("altitudeAngle", this.altitudeAngle);
        toReturn.put("azimuthAngle", this.azimuthAngle);
        return toReturn;
    }

}