/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for input.SetFilesParameters command
 */
public class SetFilesParameters {

    /**
     * Creates a new SetFilesParameters instance
     */
    public SetFilesParameters(String context, Script.SharedReference element, List<String> files) {
        this.context = context;
        this.element = element;
        this.files = files;
    }

    private final String context;

    /**
     * Gets the context property
     * @return String value
     */
    public String getContext() {
        return this.context;
    }

    private final Script.SharedReference element;

    /**
     * Gets the element property
     * @return Script.SharedReference value
     */
    public Script.SharedReference getElement() {
        return this.element;
    }

    private final List<String> files;

    /**
     * Gets the files property
     * @return List<String> value
     */
    public List<String> getFiles() {
        return this.files;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("context", this.context);
        toReturn.put("element", this.element);
        toReturn.put("files", this.files);
        return toReturn;
    }

}