/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.input;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for input.WheelScrollAction command
 */
public class WheelScrollAction implements WheelSourceAction {

    /**
     * Creates a new WheelScrollAction instance
     */
    public WheelScrollAction(Integer x, Integer y, Integer deltaX, Integer deltaY, Long duration, Input.Origin origin) {
        this.x = x;
        this.y = y;
        this.deltaX = deltaX;
        this.deltaY = deltaY;
        this.duration = duration;
        this.origin = origin;
        this.type = "scroll";
    }

    private final String type;

    /**
     * Gets the type property
     * @return String value
     */
    public String getType() {
        return this.type;
    }

    private final Integer x;

    /**
     * Gets the x property
     * @return Integer value
     */
    public Integer getX() {
        return this.x;
    }

    private final Integer y;

    /**
     * Gets the y property
     * @return Integer value
     */
    public Integer getY() {
        return this.y;
    }

    private final Integer deltaX;

    /**
     * Gets the deltaX property
     * @return Integer value
     */
    public Integer getDeltaX() {
        return this.deltaX;
    }

    private final Integer deltaY;

    /**
     * Gets the deltaY property
     * @return Integer value
     */
    public Integer getDeltaY() {
        return this.deltaY;
    }

    private final Long duration;

    /**
     * Gets the duration property
     * @return Long value
     */
    public Long getDuration() {
        return this.duration;
    }

    private final Input.Origin origin;

    /**
     * Gets the origin property
     * @return Input.Origin value
     */
    public Input.Origin getOrigin() {
        return this.origin;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("type", this.type);
        toReturn.put("x", this.x);
        toReturn.put("y", this.y);
        toReturn.put("deltaX", this.deltaX);
        toReturn.put("deltaY", this.deltaY);
        toReturn.put("duration", this.duration);
        toReturn.put("origin", this.origin);
        return toReturn;
    }

}