/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

/**
 * Represents Level in WebDriver BiDi protocol
 * as enum of "debug" / "info" / "warn" / "error"
 */
public enum Level {
    DEBUG("debug");
    INFO("info");
    WARN("warn");
    ERROR("error");

    private final String value;

    Level(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static Level fromString(String text) {
        for (Level level : Level.values()) {
            if (level.value.equalsIgnoreCase(text)) {
                return level;
            }
        }
        throw new IllegalArgumentException("No Level with value: " + text);
    }
}