/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.log;

import java.util.Map;
import java.util.HashMap;
import org.openqa.selenium.bidi.Command;
import org.openqa.selenium.bidirectional.EmptyResult;

/**
 * Auto generated class for running WebDriver BiDi log commands in Java
 */
public class LogModule {

    /**
     * WebDriver Bidi command to send command method "log.entryAdded" with parameters.
     * @url https://w3c.github.io/webdriver-bidi/#command-log-entryAdded
     * @param parameters `Entry` {@link https://w3c.github.io/webdriver-bidi/#command-log-entryAdded | command parameter}
     * @return Command object with result type for log.entryAdded
     */
    public Command<org.openqa.selenium.bidirectional.EmptyResult> EntryAdded (Entry parameters) {
        return new Command<>(
            "log.entryAdded",
            parameters.asMap(),
            org.openqa.selenium.bidirectional.EmptyResult.class
        );
    }
}