/**
 * !!! PLEASE DO NOT EDIT THIS FILE !!!
 *
 * This source file, even though checked in, is auto-generated based on the
 * current development within the WebDriver Bidi spec. Any changes to this
 * file need to come from the specification.
 */

package org.openqa.selenium.bidirectional.emulation;

import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.openqa.selenium.bidirectional.*;

/**
 * Auto-generated class for WebDriver BiDi protocol
 * Represents parameters for emulation.GeolocationCoordinates command
 */
public class GeolocationCoordinates {

    /**
     * Creates a new GeolocationCoordinates instance
     */
    public GeolocationCoordinates(Float latitude, Float longitude, Float accuracy, Object altitude, Object altitudeAccuracy, Object heading, Object speed) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.accuracy = accuracy;
        this.altitude = altitude;
        this.altitudeAccuracy = altitudeAccuracy;
        this.heading = heading;
        this.speed = speed;
    }

    private final Float latitude;

    /**
     * Gets the latitude property
     * @return Float value
     */
    public Float getLatitude() {
        return this.latitude;
    }

    private final Float longitude;

    /**
     * Gets the longitude property
     * @return Float value
     */
    public Float getLongitude() {
        return this.longitude;
    }

    private final Float accuracy;

    /**
     * Gets the accuracy property
     * @return Float value
     */
    public Float getAccuracy() {
        return this.accuracy;
    }

    private final Object altitude;

    /**
     * Gets the altitude property
     * @return Object value
     */
    public Object getAltitude() {
        return this.altitude;
    }

    private final Object altitudeAccuracy;

    /**
     * Gets the altitudeAccuracy property
     * @return Object value
     */
    public Object getAltitudeAccuracy() {
        return this.altitudeAccuracy;
    }

    private final Object heading;

    /**
     * Gets the heading property
     * @return Object value
     */
    public Object getHeading() {
        return this.heading;
    }

    private final Object speed;

    /**
     * Gets the speed property
     * @return Object value
     */
    public Object getSpeed() {
        return this.speed;
    }

    /**
     * Converts this object to a map for use with BiDi protocol
     * @return Map representation of this object
     */
    public Map<String, Object> asMap() {
        Map<String, Object> toReturn = new HashMap<>();
        toReturn.put("latitude", this.latitude);
        toReturn.put("longitude", this.longitude);
        toReturn.put("accuracy", this.accuracy);
        toReturn.put("altitude", this.altitude);
        toReturn.put("altitudeAccuracy", this.altitudeAccuracy);
        toReturn.put("heading", this.heading);
        toReturn.put("speed", this.speed);
        return toReturn;
    }

}